# ~/.config/autofile
origins:
  #the directories where files are searched for.
file_extensions:
  #pictures:
  #  endings:
  #  - ".jpeg"
  #  - ".png"
  #  - ".jpg"
  #  destination: "~/Pictures/"
  #  addDate: true
filestarts:
  #documents:
  #  directory: "~/Documents/"
  #  starts:
  #  - private
  #  - someotherthing
  #  addDate: true
plugins:
  backup:
    dotfiles:
      files:
        - "~/.config/autofile/config.yaml"
      backup_directory: "~/dotfiles/"